### ISSUE TITLE
404 link on 'publicly discoverable services' on domain expand dropdown

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/pulse#65] opened 2018-05-19 00:26 UTC
http://<url>/https/guidance/#subdomains

This anchor must have gotten pruned out from our guidance, but is still in the expansion of domain list.

![image](https://user-images.githubusercontent.com/17616596/40262918-bbf324cc-5ad9-11e8-9498-53b9ecd71f91.png)

**Comment by evadb** [comment] 2018-05-22 14:54
this is a duplicate of https://github.com/cds-snc/pulse/issues/60, closing this one

**Closed by evadb** 2018-05-22 14:54 UTC
Labels: bug
